// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkxpnxwnixztnedgnkvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5reHBueHduaXh6dG5lZGdua3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MDYxMDAsImV4cCI6MjA2NDk4MjEwMH0.jJB7yMwaCp-XlX-6f9Avsl-yM0u3prYs8k2J0ASflqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);